providers:
  openai:
    name: "OpenAI"
    api_base: "https://api.openai.com/v1"
    models:
      gpt-4o:
        name: "GPT-4o"
        context_length: 128000
        strengths: ["邏輯推理", "程式碼生成", "問題解決"]
        cost_tier: "premium"
      gpt-4o-mini:
        name: "GPT-4o Mini"
        context_length: 128000
        strengths: ["快速響應", "成本效益", "一般任務"]
        cost_tier: "standard"
      o1-preview:
        name: "o1 Preview" 
        context_length: 32768
        strengths: ["複雜推理", "數學問題", "深度分析"]
        cost_tier: "premium"
      o1-mini:
        name: "o1 Mini"
        context_length: 65536
        strengths: ["快速推理", "程式碼問題", "邏輯分析"]
        cost_tier: "standard"
        
  anthropic:
    name: "Anthropic"
    api_base: "https://api.anthropic.com/v1" 
    models:
      claude-3-5-sonnet-20241022:
        name: "Claude Sonnet-4"
        context_length: 200000
        strengths: ["系統分析", "架構設計", "程式碼審查"]
        cost_tier: "premium"
      claude-3-opus-20240229:
        name: "Claude Opus-4"
        context_length: 200000
        strengths: ["複雜推理", "創作能力", "深度分析"]
        cost_tier: "premium"
      claude-3-haiku-20240307:
        name: "Claude Haiku"
        context_length: 200000
        strengths: ["快速響應", "簡潔回答", "成本效益"]
        cost_tier: "basic"
        
  xai:
    name: "xAI"
    api_base: "https://api.x.ai/v1"
    models:
      grok-beta:
        name: "Grok Beta"
        context_length: 131072
        strengths: ["創新思維", "另類解法", "優化建議"]
        cost_tier: "standard"
        
  google:
    name: "Google AI"
    api_base: "https://generativelanguage.googleapis.com/v1"
    models:
      gemini-1.5-pro:
        name: "Gemini 1.5 Pro"
        context_length: 2000000
        strengths: ["資料處理", "分析能力", "多模態處理"]
        cost_tier: "premium"
      gemini-1.5-flash:
        name: "Gemini 1.5 Flash"
        context_length: 1000000
        strengths: ["快速處理", "高效率", "成本效益"]
        cost_tier: "standard"

# 預設配置
defaults:
  provider: "anthropic"
  model: "claude-3-5-sonnet-20241022"
  role: "system_architect"
  temperature: 0.7
  max_tokens: 4000
  timeout: 60

# 成本層級定義
cost_tiers:
  basic:
    description: "基本層級，適合簡單任務"
    recommended_for: ["快速問答", "簡單程式碼", "一般協助"]
  standard:
    description: "標準層級，適合大多數開發任務"
    recommended_for: ["功能開發", "程式碼審查", "問題解決"]
  premium:
    description: "進階層級，適合複雜任務"
    recommended_for: ["架構設計", "複雜推理", "深度分析"]